import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    id: uuid(),
    bestSelling: true,
    name: "APPLE IPHONE 12 (BLACK, 16Gb)",
    brand: "APPLE",
    price: 79000,
    type: "IOS",
    topProcessor: true,
    camera: "48mp",
    gamingGPU: true,
    processor: "A14 Bionic",
    image:
      "./Assets/Images/apple-iphone-12-mini-dummyapplefsn-original-imafwgbfwyzztfnh.jpeg",
    FASTDELIVERY: true,
    inStock: false,
    rating: 5,
  },
  {
    id: uuid(),
    bestSelling: true,
    name: "ONE PLUS 9 Pro (Morning mist)",
    brand: "ONE PLUS",
    price: 49000,
    type: "ANDROID",
    camera: "48mp",
    topProcessor: true,
    gamingGPU: true,
    processor: "MediaTek",
    image: "./Assets/Images/63796658-96e1-48c4-8b7e-4aa910e81c13_182x182.jpg",
    FASTDELIVERY: true,
    inStock: true,
    rating: 4,
  },
  {
    id: uuid(),
    bestSelling: false,
    name: "SAMSUNG (BLACK 6GB)",
    brand: "SAMSUNG",
    price: 9000,
    type: "ANDROID",
    camera: "16mp",
    topProcessor: false,
    gamingGPU: false,
    processor: "SnapDragon",
    image:
      "./Assets/Images/305e4829-81b4-423d-88d9-f550bab2e15721151133_182x182.jpg",
    FASTDELIVERY: false,
    inStock: true,
    rating: 4,
  },
  {
    id: uuid(),
    bestSelling: false,
    name: "SAMSUNG (BLACK 8GB)",
    brand: "SAMSUNG",
    price: 14000,
    type: "ANDROID",
    camera: "16mp",
    topProcessor: false,
    gamingGPU: false,
    processor: "MediaTek",
    image:
      "./Assets/Images/305e4829-81b4-423d-88d9-f550bab2e15721151133_182x182.jpg",
    FASTDELIVERY: true,
    inStock: true,
    rating: 3,
  },
  {
    id: uuid(),
    bestSelling: true,
    name: "ASUS ROG phone 5 (Black, 16Gb)",
    brand: "ASUS",
    price: 56000,
    type: "ANDROID",
    camera: "48mp",
    topProcessor: true,
    gamingGPU: true,
    processor: "SnapDragon",
    image:
      "./Assets/Images/rog-phone-5-zs673ks-1a053in-asus-original-imagff5hufbu4eg5.jpeg",
    FASTDELIVERY: true,
    inStock: true,
    rating: 5,
  },
  {
    id: uuid(),
    bestSelling: false,
    name: "MI redmi (Black, 8Gb)",
    brand: "MI",
    price: 13000,
    type: "ANDROID",
    camera: "12mp",
    topProcessor: false,
    gamingGPU: false,
    processor: "SnapDragon",
    image:
      "./Assets/Images/9i-sport-mzb0a5iin-redmi-original-imag785qegs5ghyy.jpeg",
    FASTDELIVERY: false,
    inStock: true,
    rating: 3,
  },
  {
    id: uuid(),
    bestSelling: false,
    name: "NOKIA TA-1304 (Black)",
    brand: "NOKIA",
    price: 4000,
    type: "FEATURE PHONE",
    topProcessor: false,
    camera: "4mp",
    gamingGPU: false,
    processor: null,
    image: "./Assets/Images/nokia-105-ss-105-ss-original-imaewa2ykrbdaryt.jpeg",
    FASTDELIVERY: true,
    inStock: false,
    rating: 4,
  },
  {
    id: uuid(),
    bestSelling: false,
    name: "LAVA A1 Josh (Black)",
    brand: "LAVA",
    price: 3000,
    type: "FEATURE PHONE",
    topProcessor: false,
    camera: "4mp",
    gamingGPU: false,
    processor: null,
    image:
      "./Assets/Images/a1-josh-2021-lf1001-lava-original-imag62vfzav9ttrb.jpeg",
    FASTDELIVERY: true,
    inStock: true,
    rating: 2,
  },
  {
    id: uuid(),
    bestSelling: true,
    name: "Asus ROG II (Black, 8Gb)",
    brand: "Asus",
    price: 40000,
    type: "ANDROID",
    topProcessor: true,
    gamingGPU: true,
    camera: "48mp",
    processor: "MediaTek",
    image:
      "./Assets/Images/asus-rog-phone-ii-zs660kl-1a017in-original-imafkkbmyuv5vygg.jpeg",
    FASTDELIVERY: true,
    inStock: false,
    rating: 5,
  },
  {
    id: uuid(),
    bestSelling: false,
    name: "Samsung galaxy Z fold",
    brand: "Samsung",
    price: 60000,
    type: "ANDROID",
    topProcessor: true,
    gamingGPU: false,
    camera: "48mp",
    processor: "MediaTek",
    image:
      "./Assets/Images/galaxy-z-fold3-5g-sm-f926bzkdinu-samsung-original-imag662a7zgxn2fv.jpeg",
    FASTDELIVERY: false,
    inStock: true,
    rating: 3,
  },
  {
    id: uuid(),
    bestSelling: false,
    name: "Vivo X60 (Black, 16Gb)",
    brand: "Vivo",
    price: 35000,
    type: "ANDROID",
    topProcessor: false,
    gamingGPU: false,
    camera: "24mp",
    processor: "MediaTek",
    image: "./Assets/Images/x60-v2045-vivo-original-imagfht4a9bggbxb.jpeg",
    FASTDELIVERY: true,
    inStock: true,
    rating: 5,
  },
  {
    id: uuid(),
    bestSelling: false,
    name: "Motorolla G31 (Blue, 4Gb)",
    brand: "Motorolla",
    price: 9000,
    type: "ANDROID",
    topProcessor: true,
    gamingGPU: true,
    camera: "24mp",
    processor: "SnapDragn",
    image: "./Assets/Images/-original-imag95y4cutf7dc6.jpeg",
    FASTDELIVERY: false,
    inStock: true,
    rating: 4,
  },
  {
    id: uuid(),
    bestSelling: false,
    name: "Realme C11 (Black, 4Gb)",
    brand: "Realme",
    price: 13000,
    type: "ANDROID",
    gamingGPU: false,
    topProcessor: false,
    camera: "12mp",
    processor: "MediaTek",
    image:
      "./Assets/Images/c11-2021-rmx3231-realme-original-imag4j4yrdt7d9cj.jpeg",
    FASTDELIVERY: true,
    inStock: true,
    rating: 4,
  },
  {
    id: uuid(),
    bestSelling: false,
    name: "APPLE iPhone 12 (Black, 32Gb)",
    brand: "APPLE",
    price: 80000,
    type: "IOS",
    gamingGPU: true,
    topProcessor: true,
    camera: "48mp",
    FASTDELIVERY: false,
    processor: "A14 Bionic",
    image:
      "./Assets/Images/apple-iphone-12-mini-dummyapplefsn-original-imafwgbfwyzztfnh.jpeg",
    inStock: true,
    rating: 4,
  },
];
